# Generated by Django 4.2.7 on 2023-12-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSheetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_sheet_score', models.FloatField(verbose_name='نمره')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_sheet_scores', to='panel.student', verbose_name='دانش آموز')),
                ('taught_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.taughtclass', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'نمره کارنامه',
                'verbose_name_plural': 'نمرات کارنامه',
            },
        ),
    ]
