# Generated by Django 4.2.7 on 2023-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_reportsheetscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsheetscore',
            name='score_type',
            field=models.IntegerField(choices=[(1, 'تکوینی'), (2, 'نوبت'), (3, 'پایانی')], default=1, verbose_name='نوع نمره'),
            preserve_default=False,
        ),
    ]
