# Generated by Django 4.2.7 on 2023-12-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_reportsheetscore_score_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsheetscore',
            name='report_sheet_score',
            field=models.FloatField(default=0, verbose_name='نمره'),
        ),
    ]
