# Generated by Django 4.2.7 on 2024-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_observer',
            field=models.BooleanField(default=False, verbose_name='نماینده است؟'),
            preserve_default=False,
        ),
    ]
