# Generated by Django 4.2.7 on 2023-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/profiles')),
                ('name', models.CharField(max_length=158)),
                ('description', models.TextField(max_length=2048)),
            ],
            options={
                'verbose_name': 'دستاورد علمی پژوهشی',
                'verbose_name_plural': 'دستاورد های علمی پژوهشی',
            },
        ),
    ]
